name: Epic
description: A large delivery that groups stories
type: Epic
projects: ["Storagie/5"]
body:
  - type: textarea
    id: context
    attributes:
      label: Contexto
    validations:
      required: true
  - type: textarea
    id: questions
    attributes:
      label: Perguntas
      value: "- [ ] "
  - type: textarea
    id: acceptance
    attributes:
      label: Critérios de aceite
      value: "- [ ] "
  - type: textarea
    id: out-of-scope
    attributes:
      label: Fora do escopo
      value: "- "
